//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamro_dokan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBanner
    {
        public int BannerId { get; set; }
        public string Header { get; set; }
        public string Caption { get; set; }
        public string Path { get; set; }
    }
}
