//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamro_dokan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Everything
    {
        public int CartId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public int Expr1 { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Color { get; set; }
        public string Img { get; set; }
        public string Brand { get; set; }
    }
}
